#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/andrewlooka/opt/anaconda3/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/andrewlooka/opt/anaconda3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/andrewlooka/Documents/GitHub/lindroos2018/x86_64/.libs/libnrnmech.so" "$@"
